import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from '../components/Nav'
import Header from '../components/Header'
import PricePlan from '../components/SubscriptionPlan'
import Footer from '../components/Footer'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <html className={styles.container} >
        <Head>
          <title>Borealis</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" />
        </Head>
        <main className={styles.main}>
          <div className={styles.header}>
            <Nav />
            <div className={styles.logoHeader}>
              <Image src="/logoWorkspace.png" alt="Spare workspace logo" width={250} height={60} />
            </div>
            <Header />
            <PricePlan />
            <Footer />
          </div>
        </main>
    </html>
  )
}

export default Home
